spring.application.name=ms-user

spring.datasource.url=jdbc:h2:mem:usersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sasa

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true

app.user.default.roles=ROLE_USER,ROLE_GUEST,ROLE_VIEWER

server.port=8080